apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluacioncredito-deployment
  labels:
    app: evaluacioncredito-deployment
spec:
  selector:
    matchLabels:
      app: evaluacioncredito-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: evaluacioncredito-deployment
    spec:
      containers:
        - name: nuevosUsuarios-service
          image: ttoto104/evaluacioncredito-service
          ports:
            - containerPort: 8097